### ISSUE TITLE
Best way to extend styles?

### ISSUE THREAD

**Issue by cscd98** [webgriffe/theme-bootstrap#14]
My theme inherits from yours in theme.xml

But, whatever I create in my theme in web/css, web/css/source, web/css/bootstrap/css etc I cannot seem to extend _theme.less

I have tried _extend.less but this does not seem to work

Any ideas?

**Comment by mmenozzi** [comment]
Yes because this theme completely removes the Magento's styles in favor of bootstrap. To customize the look and feel you should override the bootstrap-theme.less creating a bootstrap theme.
