### ISSUE TITLE
Bootstrap 4 support

### ISSUE THREAD

**Issue by czettnersandor** [webgriffe/theme-bootstrap#16]
Thank you for this great base theme!

I'm working on converting it to Bootstrap 4. Is it something you would like to merge back?

**Comment by mmenozzi** [comment]
Yes sure, thank you!
Maybe we'll merge it in a new version's branch.

**Comment by apomili** [comment]
Hello, news about this request?

**Comment by czettnersandor** [comment]
@KickinAss I don't have anything useful to show just yet.

**Comment by chrisastley** [comment]
Any progress on this?

**Comment by mmenozzi** [comment]
Hi @chrisastley, we're not working on this right now. It's a work of  @czettnersandor but we don't know the status of the task.
I'm also going to close this is issue because it's not something that we're taking care of.

**Comment by czettnersandor** [comment]
@chrisastley I started this for a client but they decided to buy a template instead. Would you take it forward? It's not too much work, I think. There are different css classes and the markup is different as well. I'm happy to help in my free time as this would be a great starter theme.
