### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by arest** [webgriffe/theme-bootstrap#7]
Problem 1
    - Installation request for webgriffe/theme-frontend-bootstrap dev-master -> satisfiable by webgriffe/theme-frontend-bootstrap[dev-master].
    - webgriffe/theme-frontend-bootstrap dev-master requires webgriffe/module-bootstrap-menu ^1.0 -> no matching package found.

**Comment by mmenozzi** [comment]
The module-bootstrap-menu is not on packagist yet.
Did you add the module-bootstrap-menu vcs repository to your composer.json?
If not please add it with the command

composer config repo.bootstrap-module vcs https://github.com/webgriffe/module-bootstrap-menu.git

**Comment by loredev10** [comment]
I have the same error even after I added the repository.

**Comment by mmenozzi** [comment]
@MurKit could you please post your `composer.json` file?

**Comment by loredev10** [comment]
@mmenozzi yes, here it is https://paste2.org/VEtsczy8

**Comment by mmenozzi** [comment]
You miss the module-bootstrap repository in the repository section. You only have the theme-bootstrap repository. Please note that module-bootstrap and theme-bootstrap are two different packages so you need both in the repository section.

**Comment by loredev10** [comment]
Didn't notice that we need two repositories. That solved the problem.

**Comment by mmenozzi** [comment]
Good!
